runtime: python311

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.server:app

env_variables:
  ENVIRONMENT: "gcp"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
