runtime: python311

env_variables:
  MCP_SERVER_HOST: "0.0.0.0"
  MCP_SERVER_PORT: "8080"
  # IMPORTANT: Set OPENWEATHER_API_KEY via gcloud or Secret Manager
  # Do not commit actual API keys to version control!

entrypoint: python main.py server --port 8080

# Optional: Configure automatic scaling
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
